# 被动做市策略配置文件

# 策略配置
strategy:
  symbol: "BTCUSDT"
  min_spread: 0.002  # 0.2%
  max_spread: 0.004  # 0.4%
  min_order_value: 10000  # 最小订单价值（USDT）
  target_orders_per_side: 1  # 每边目标订单数
  drift_threshold: 0.005  # 0.5%
  rebalance_interval: 5  # 重新平衡间隔（秒）

# 价格计算配置
price:
  method: "HYBRID"  # TWAP, VWAP, EMA, HYBRID
  window_size: 100  # 数据窗口大小
  smoothing_factor: 0.1  # 平滑因子
  change_threshold: 0.001  # 价格变化阈值
  anomaly_threshold: 0.05  # 异常价格阈值

# 执行配置
execution:
  symbol: "BTCUSDT"
  worker_count: 4  # 工作器数量
  batch_size: 10  # 批处理大小
  rate_limit: 10  # 每秒请求数限制
  max_retries: 3  # 最大重试次数
  retry_delay: 1.0  # 重试延迟（秒）

# 风险配置
risk:
  max_position: 1.0  # 最大持仓（BTC）
  max_order_count: 100  # 最大订单数
  max_daily_loss: 1000  # 最大日损失（USDT）
  max_price_change: 0.1  # 最大价格变化（10%）
  check_interval: 5  # 检查间隔（秒）

# API配置
api:
  key: "your_api_key_here"
  secret: "your_api_secret_here"
  testnet: true  # 使用测试网

# 系统配置
system:
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "market_making.log"
  metrics_enabled: true 